version: "3.9"

services:
  android:
    build: .
    stdin_open: true
    tty: true
    volumes:
      - ~/.android/:/root/.android/
      - ./simple-rt-android:/root/source
    environment:
      - ANDROID_SDK_ROOT=/root/.android/
      - ANDROID_NDK_HOME=/root/.android/ndk-bundle
      - ANDROID_HOME=/root/.android
