version: "3.9"

services:
  android:
    build: .
    volumes:
      - ~/.android/sdk:/root/.android/sdk
      - ./simple-rt-android:/root/source
    environment:
      - ANDROID_SDK_ROOT=/root/.android/sdk
      - ANDROID_NDK_HOME=/root/.android/sdk/ndk-bundle
      - ANDROID_HOME=/root/.android
